# Generated by Django 5.2.11 on 2026-05-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doselog',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='doselog',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='doselog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed')], default='pending', max_length=10),
        ),
    ]
