# Generated by Django 5.2.11 on 2026-05-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_doselog_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doselog',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='schedules.medicationschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doselog',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
