# Generated by Django 5.2.5 on 2026-06-02 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_doselog_schedule_doselog_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doselog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
