# Generated by Django 5.2.5 on 2026-05-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='push_token',
        ),
    ]
